# Generated by Django 2.2.13 on 2020-07-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200702_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.TextField(blank=True, default='Owner'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.BooleanField(default=False),
        ),
    ]
