# Generated by Django 2.2.13 on 2020-07-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200705_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
