# Generated by Django 2.2.13 on 2020-07-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_puser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
