# Generated by Django 2.2.13 on 2020-07-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_remove_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='puser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='username_project',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
