# Generated by Django 2.2.13 on 2020-07-10 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200710_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_member', through='projects.UserProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
