# Generated by Django 2.2.13 on 2020-07-10 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200710_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
