# Generated by Django 2.2.13 on 2020-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.BooleanField(default=True),
        ),
    ]
