# Generated by Django 2.2.13 on 2020-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='number',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date',
            field=models.TextField(default='AddDate'),
        ),
    ]
