# Generated by Django 2.2.13 on 2020-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_auto_20200629_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='goal',
            field=models.TextField(default='AddGoal'),
        ),
    ]
