# Generated by Django 2.2.13 on 2020-07-02 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200702_0045'),
        ('sprints', '0004_auto_20200630_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='project_id',
        ),
        migrations.AddField(
            model_name='sprint',
            name='project_sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
