# Generated by Django 2.2.13 on 2020-07-04 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_auto_20200702_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
