# Generated by Django 2.2.13 on 2020-07-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200721_2100'),
        ('sprints', '0006_auto_20200704_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='project_sprint',
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(),
        ),
    ]
