# Generated by Django 2.2.13 on 2020-07-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0007_auto_20200726_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['number']},
        ),
    ]
