# Generated by Django 2.2.13 on 2020-07-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0009_auto_20200727_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['start_date']},
        ),
    ]
