# Generated by Django 2.2.13 on 2020-07-30 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprints', '0010_auto_20200729_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprint')),
            ],
            options={
                'ordering': ['completed', 'start_date'],
            },
        ),
    ]
