# Generated by Django 2.2.13 on 2020-07-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'start_date', 'id']},
        ),
    ]
