# Generated by Django 2.2.13 on 2020-07-31 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200730_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'start_date', 'id']},
        ),
    ]
